[project]
name = 'clarity-master-whoabuddy'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.ex3-01-maps-and-variables]
path = 'contracts/ex3-01-maps-and-variables.clar'
clarity_version = 2
epoch = 2.5

[contracts.ex3-02-maps-and-variables]
path = 'contracts/ex3-02-maps-and-variables.clar'
clarity_version = 2
epoch = 2.5

[contracts.ex4-01]
path = 'contracts/ex4-01.clar'
clarity_version = 2
epoch = 2.5

[contracts.ex4-02]
path = 'contracts/ex4-02.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
